#!/usr/bin/env bun
/**
 * Obsidian Bridge — Writes composite skill outputs to SecondBrain wiki.
 *
 * After a composite skill completes, this bridge:
 * 1. Reads the skill output from .productionos/domains/{composite}/
 * 2. Formats it as an Obsidian wiki page with backlinks
 * 3. Writes to ~/SecondBrain/wiki/domains/{composite}/
 * 4. Updates the domain index page
 *
 * Usage:
 *   bun run scripts/obsidian-bridge.ts write [domain] [action] [title]
 *   bun run scripts/obsidian-bridge.ts index [domain]
 *   bun run scripts/obsidian-bridge.ts search [query]
 *   bun run scripts/obsidian-bridge.ts config
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

// Configurable vault path — check pos-config, env var, then default
function getVaultPath(): string {
  const configPath = join(
    process.env.PRODUCTIONOS_HOME || join(process.env.HOME || "", ".productionos"),
    "config",
    "settings.json"
  );
  try {
    const config = JSON.parse(readFileSync(configPath, "utf-8"));
    if (config.vault_path) return config.vault_path;
  } catch { /* use fallback */ }
  return process.env.SECONDBRAIN_PATH || process.env.OBSIDIAN_VAULT || join(process.env.HOME || "", "SecondBrain");
}

const VAULT = getVaultPath();
const WIKI_DIR = join(VAULT, "wiki", "domains");
const POS_DOMAINS = join(
  process.env.PRODUCTIONOS_HOME || join(process.env.HOME || "", ".productionos"),
  "domains"
);

interface WikiPage {
  title: string;
  domain: string;
  action: string;
  date: string;
  content: string;
  backlinks: string[];
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function formatWikiPage(page: WikiPage): string {
  const backlinks = page.backlinks.map((b) => `[[${b}]]`).join(", ");
  return `---
title: "${page.title}"
domain: ${page.domain}
action: ${page.action}
date: ${page.date}
tags: [productionos, ${page.domain}, ${page.action}]
---

# ${page.title}

**Domain:** [[${page.domain}]] | **Action:** ${page.action} | **Date:** ${page.date}

${page.content}

---
## Related
${backlinks || "No backlinks yet."}

*Generated by ProductionOS obsidian-bridge*
`;
}

function updateDomainIndex(domain: string): void {
  const domainDir = join(WIKI_DIR, domain);
  if (!existsSync(domainDir)) return;

  const pages = readdirSync(domainDir)
    .filter((f) => f.endsWith(".md") && f !== "_index.md")
    .sort()
    .reverse();

  const entries = pages.map((f) => {
    const name = f.replace(".md", "");
    return `- [[${domain}/${name}|${name}]]`;
  });

  const index = `---
title: "${domain} Domain"
tags: [productionos, ${domain}]
---

# ${domain}

ProductionOS composite domain. ${pages.length} wiki pages.

## Pages
${entries.join("\n")}

## Memory
- Profile: \`~/.productionos/domains/${domain}/profile.yml\`
- History: \`~/.productionos/domains/${domain}/\`
- Learnings: \`~/.productionos/domains/${domain}/learnings.jsonl\`
`;

  writeFileSync(join(domainDir, "_index.md"), index);
}

// === Commands ===

const [, , command, ...args] = process.argv;

switch (command) {
  case "write": {
    const [domain, action, ...titleParts] = args;
    if (!domain || !action) {
      console.error("Usage: write [domain] [action] [title]");
      process.exit(1);
    }

    const title = titleParts.join(" ") || `${domain}-${action}-${new Date().toISOString().slice(0, 10)}`;
    const domainDir = join(WIKI_DIR, domain);
    mkdirSync(domainDir, { recursive: true });

    // Read domain memory for context
    const memoryDir = join(POS_DOMAINS, domain);
    let memoryContext = "";
    if (existsSync(join(memoryDir, "profile.yml"))) {
      memoryContext = `\n## Domain Profile\n\`\`\`yaml\n${readFileSync(join(memoryDir, "profile.yml"), "utf-8")}\n\`\`\`\n`;
    }

    // Read from stdin if piped, otherwise create placeholder
    let content = "";
    try {
      if (!process.stdin.isTTY) {
        content = readFileSync("/dev/stdin", "utf-8");
      }
    } catch { /* no stdin */ }

    if (!content) {
      content = `*Skill output will be written here after /${domain} ${action} completes.*${memoryContext}`;
    }

    const page: WikiPage = {
      title,
      domain,
      action,
      date: new Date().toISOString().slice(0, 10),
      content,
      backlinks: [domain, `${domain}/${action}`],
    };

    const filename = `${slugify(title)}.md`;
    writeFileSync(join(domainDir, filename), formatWikiPage(page));
    updateDomainIndex(domain);

    console.log(JSON.stringify({ ok: true, path: join(domainDir, filename), domain, action }));
    break;
  }

  case "index": {
    const domain = args[0];
    if (domain) {
      updateDomainIndex(domain);
      console.log(JSON.stringify({ ok: true, domain }));
    } else {
      // Update all domain indexes
      if (existsSync(WIKI_DIR)) {
        const domains = readdirSync(WIKI_DIR).filter((d) =>
          existsSync(join(WIKI_DIR, d)) && readdirSync(join(WIKI_DIR, d)).some((f) => f.endsWith(".md"))
        );
        domains.forEach(updateDomainIndex);
        console.log(JSON.stringify({ ok: true, domains }));
      }
    }
    break;
  }

  case "search": {
    const query = args.join(" ").toLowerCase();
    if (!query) {
      console.error("Usage: search [query]");
      process.exit(1);
    }

    const results: Array<{ file: string; domain: string; matches: number }> = [];
    if (existsSync(WIKI_DIR)) {
      for (const domain of readdirSync(WIKI_DIR)) {
        const domainDir = join(WIKI_DIR, domain);
        try {
          for (const file of readdirSync(domainDir)) {
            if (!file.endsWith(".md")) continue;
            const content = readFileSync(join(domainDir, file), "utf-8").toLowerCase();
            const matches = content.split(query).length - 1;
            if (matches > 0) {
              results.push({ file: `${domain}/${file}`, domain, matches });
            }
          }
        } catch { /* skip non-directories */ }
      }
    }

    results.sort((a, b) => b.matches - a.matches);
    console.log(JSON.stringify({ query, results: results.slice(0, 20), total: results.length }));
    break;
  }

  case "config": {
    console.log(JSON.stringify({
      vault: VAULT,
      wiki: WIKI_DIR,
      domains: POS_DOMAINS,
      exists: {
        vault: existsSync(VAULT),
        wiki: existsSync(WIKI_DIR),
        domains: existsSync(POS_DOMAINS),
      },
    }, null, 2));
    break;
  }

  default:
    console.log(`Obsidian Bridge — ProductionOS -> SecondBrain Wiki

Commands:
  write [domain] [action] [title]   Write skill output to wiki
  index [domain]                    Update domain index page
  search [query]                    Search wiki pages
  config                            Show paths and status
`);
}
